### ISSUE TITLE
Scripf not working on OpenSuSE Leap 15.6 (AMD64)

### ISSUE THREAD

**Issue by JacekRuzyczka** [mosssahel/Signal-Desktop-AppImage#4]
I followed your instruction, but first, the script complained about a missing `yarn`, then about a missing env variable `NVM_DIR` I had to add to my `.zshrc`:

```sh
export NVM_DIR="$HOME/.nvm"
[ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
```

…but after installing `yarn` and defining `NVM_DIR`, I ended up with a whole load of error messages I don't understand. Most of them come from `yarn`, not from your script:

```java
Now using node v14.16.0 (npm v)
internal/modules/cjs/loader.js:883
  throw err;
  ^

Error: Cannot find module 'node:path'
Require stack:
- /home/jacek/.nvm/versions/node/v14.16.0/lib/node_modules/npm/lib/cli.js
- /home/jacek/.nvm/versions/node/v14.16.0/lib/node_modules/npm/bin/npm-cli.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/home/jacek/.nvm/versions/node/v14.16.0/lib/node_modules/npm/lib/cli.js:10:18)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/jacek/.nvm/versions/node/v14.16.0/lib/node_modules/npm/lib/cli.js',
    '/home/jacek/.nvm/versions/node/v14.16.0/lib/node_modules/npm/bin/npm-cli.js'
  ]
}
internal/modules/cjs/loader.js:883
  throw err;
  ^

Error: Cannot find module 'node:path'
Require stack:
- /home/jacek/.nvm/versions/node/v14.16.0/lib/node_modules/npm/lib/cli.js
- /home/jacek/.nvm/versions/node/v14.16.0/lib/node_modules/npm/bin/npm-cli.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/home/jacek/.nvm/versions/node/v14.16.0/lib/node_modules/npm/lib/cli.js:10:18)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/jacek/.nvm/versions/node/v14.16.0/lib/node_modules/npm/lib/cli.js',
    '/home/jacek/.nvm/versions/node/v14.16.0/lib/node_modules/npm/bin/npm-cli.js'
  ]
}
Klone nach 'Signal-Desktop'...
remote: Enumerating objects: 207254, done.
remote: Counting objects: 100% (2756/2756), done.
remote: Compressing objects: 100% (486/486), done.
remote: Total 207254 (delta 2529), reused 2270 (delta 2270), pack-reused 204498 (from 3)
Empfange Objekte: 100% (207254/207254), 876.24 MiB | 11.67 MiB/s, fertig.
Löse Unterschiede auf: 100% (139549/139549), fertig.
Updated Git hooks.
Git LFS initialized.
internal/modules/cjs/loader.js:883
  throw err;
  ^

Error: Cannot find module 'node:path'
Require stack:
- /home/jacek/.nvm/versions/node/v14.16.0/lib/node_modules/npm/lib/cli.js
- /home/jacek/.nvm/versions/node/v14.16.0/lib/node_modules/npm/bin/npm-cli.js
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:880:15)
    at Function.Module._load (internal/modules/cjs/loader.js:725:27)
    at Module.require (internal/modules/cjs/loader.js:952:19)
    at require (internal/modules/cjs/helpers.js:88:18)
    at Object.<anonymous> (/home/jacek/.nvm/versions/node/v14.16.0/lib/node_modules/npm/lib/cli.js:10:18)
    at Module._compile (internal/modules/cjs/loader.js:1063:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
    at Module.load (internal/modules/cjs/loader.js:928:32)
    at Function.Module._load (internal/modules/cjs/loader.js:769:14)
    at Module.require (internal/modules/cjs/loader.js:952:19) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/jacek/.nvm/versions/node/v14.16.0/lib/node_modules/npm/lib/cli.js',
    '/home/jacek/.nvm/versions/node/v14.16.0/lib/node_modules/npm/bin/npm-cli.js'
  ]
}
yarn cache v1.22.19
success Cleared cache.
Done in 0.04s.
yarn install v1.22.19
info No lockfile found.
[1/6] Validating package.json...
error signal-desktop@7.81.0-alpha.1: The engine "node" is incompatible with this module. Expected version "22.20.0". Got "14.16.0"
error Found incompatible module.
info Visit https://yarnpkg.com/en/docs/cli/install for documentation about this command.
yarn run v1.22.19
error Command "grunt" not found.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
yarn run v1.22.19
error Command "build:webpack" not found.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
yarn run v1.22.19
error signal-desktop@7.81.0-alpha.1: The engine "node" is incompatible with this module. Expected version "22.20.0". Got "14.16.0"
error Commands cannot run with an incompatible environment.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
Output is in Signal-Desktop/release/

```

What's wrong?
